//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerCAT.PackageDeployer.Package.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerCAT.PackageDeployer.Package.Resources.ConfigSettings", typeof(ConfigSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;name&quot;: &quot;powercat-automation-kit&quot;,
        ///      &quot;description&quot;: &quot;powercat-automation-kit&quot;,
        ///      &quot;solutions&quot;: [
        ///        {
        ///          &quot;name&quot;: &quot;AutomationCoEMain&quot;,
        ///          &quot;importorder&quot;: &quot;1&quot;,
        ///          &quot;publishworkflows-activate-plugins&quot;: &quot;true&quot;,
        ///          &quot;overwrite-unmanaged-customizations&quot;: &quot;true&quot;,
        ///          &quot;missing-dependency-behavior&quot;: &quot;skip&quot;,
        ///          &quot;import-mode&quot;: &quot;async&quot;
        ///        },
        ///        {
        ///          &quot;name&quot;: &quot;AutomationCoESatellite&quot;,
        ///          &quot;importorder&quot;: &quot;2&quot;,
        ///          &quot;publish [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powercat_automation_kit {
            get {
                return ResourceManager.GetString("powercat-automation-kit", resourceCulture);
            }
        }
    }
}
