# Pipeline to create a Github release for the CoE Starter Kit solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number
- name: CloseMilestoneIssues
  type: boolean
  default: false
- name: DraftRelease
  type: boolean
  default: true
- name: HotfixReleaseNumber
  type: number
  default: 0
- name: PrepareAppSourcePackage
  type: boolean
  default: false
  
trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: main # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: powercat-alm # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
pool:
  vmImage: 'windows-2019'

variables:
- group: alm-accelerator-variable-group

steps:
# Checkout our GitHub Branch
- checkout: self
  displayName: 'Checkout Source Branch'

# Download the artifacts from the latest deployment of CreatorKitCore to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'Creator-kit'
    pipeline: '56' #Production buildId
    runVersion: 'latest'
    patterns: '**/CreatorKitCore*.zip'
  displayName: 'Download Creator Kit Core solution'

# Download the artifacts from the latest deployment of CreatorKitReferencesCanvas to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'Creator-kit'
    pipeline: '59' #Production buildId
    runVersion: 'latest'
    patterns: '**/CreatorKitReferencesCanvas*.zip'
  displayName: 'Download Creator Kit Canvas solution'

# Download the artifacts from the latest deployment of CreatorKitReferencesMDA to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'Creator-kit'
    pipeline: '62' #Production buildId
    runVersion: 'latest'
    patterns: '**/CreatorKitReferencesMDA*.zip'
  displayName: 'Download Creator Kit Model solution'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory

    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory

    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Build.SourcesDirectory)\powercat-creator-kit\CreatorKitResources\Release\Collateral\CreatorKit\*.*' -Destination '$(Pipeline.Workspace)\assetstaging'

    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\CreatorKit.zip'
    }
    Compress-Archive @compress

    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\releaseassets'
    Remove-Item $(Pipeline.Workspace)\drop\*managed.zip -Recurse -Force -Confirm:$false
    Remove-Item $(Pipeline.Workspace)\assetstaging -Recurse -Force -Confirm:$false
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory

    Copy-Item '$(Pipeline.Workspace)/drop/CreatorKitCore*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Pipeline.Workspace)/drop/CreatorKitReferencesCanvas*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Pipeline.Workspace)/drop/CreatorKitReferencesMDA*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    
    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)/releaseassets/CreatorKit-Unmanaged.zip'
    }
    Compress-Archive @compress
  displayName: 'Prepare release assets'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    gitHubApiUrl: 'microsoft/powercat-creator-kit'
    solutionName: 'CreatorKit'
    solutionDisplayName: 'Creator Kit'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'powercat-alm'
    releaseNotesPath: 'powercat-creator-kit/CreatorKitResources/Release/Notes/'
    issueClosingComment: 'This has been fixed in the latest release.'
    closeIssues: ${{parameters.CloseMilestoneIssues}}
    isDraft: ${{parameters.DraftRelease}}
    isPreRelease: false
    hotfixReleaseNumber: ${{parameters.HotfixReleaseNumber}}
    queryHeadingDelimited: ""
    prepareAppSourcePackage: ${{parameters.PrepareAppSourcePackage}}
